services:
  - type: web
    name: checkin-bot
    runtime: docker
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SFTP_HOST
        sync: false
      - key: SFTP_PORT
        value: "2022"
      - key: SFTP_USER
        sync: false
      - key: SFTP_PASS
        sync: false
      - key: SYNC_INTERVAL
        value: "900"
