services:
  - type: web
    name: dcbot
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_IDS
        value: ""
      - key: SFTP_HOST
        sync: false
      - key: SFTP_PORT
        value: "2022"
      - key: SFTP_USER
        sync: false
      - key: SFTP_PASS
        sync: false
      - key: SYNC_INTERVAL
        value: "900"
